config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create edit update]

  root 'clients#index'

  resources :contacts
  resources :abouts
  resources :services
  resources :reviews do
    resources :comments, except: %i[new show]
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :phone, presence :true, uniqueness: true, length: {minimum:11}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review

  validates :body, presence: true, length: {minimum: 5}
 
  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: {minimum:2}
  validates :email, presence: true, uniqueness: true
  validates :body, presence: true, length: {minimum: 5}
end

app/models/review.rb
class Review < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :body, presence: true, length: {minimum: 5}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :old_password, :remember_token

  has_secure_password validations: false

  validate :password_presence
  validate :correct_old_password, on: :update, if: -> { password.present? }
  validates :password, confirmation: true, allow_blank: true

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validate :password_complexity

  def remember_me
    self.remember_token = SecureRandom.urlsafe_base64
    update_column :remember_token_digest, digest(remember_token)
  end

  def forget_me
    update_column :remember_token_digest, nil
    self.remember_token = nil
  end

  def remember_token_authenticated?(remember_token)
    return false unless remember_token_digest.present?

    BCrypt::Password.new(remember_token_digest).is_password?(remember_token)
  end

  private

  def digest(string)
    cost = if ActiveModel::SecurePassword
              .min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add :old_password, 'не верный'
  end

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

    msg = 'требование сложности не соблюдено. Длина должна быть от 8 до 70 символов' \
    'и включать: 1 прописную, 1 строчную, 1 цифру и 1 специальный символ.'

    errors.add :password, msg
  end

  def password_presence
    errors.add(:password, :blank) if password_digest.blank?
  end
end

app/controllers/abouts_controller.rb
# frozen_string_literal: true

class AboutsController < ApplicationController
  def index
    
  end
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  def index; 

  end

  def def(_new)
    @user = User.new
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  # избегаем дублирования кода с помощью before_action и находим review и comment по id до запуска контроллера. 
  # Важен порядок Экшенов! Снаяала ответ, а потом привязанный к нему комментарий!
  before_action :set_review!
  before_action :set_comment!, except: :create

  def create
    @comment = @review.comments.build comment_params
    if @comment.save
      flash[:warning] = "Комментарий создан"
      redirect_to review_path(@review)
    else
      # Определяем переменную для того чтобы можно было отрендерить Show, так как Show в отличии 
      # от redirect_to не предоставляет никакого маршрута, а просто выводит на экран инфу
      @comments = @review.comments.order created_at: :desc 
      render 'reviews/show'
    end
  end

  def edit
  end

  def update
    if @comment.update comment_params
      flash[:warning] = "Ваш комментарий обновлен!"
      redirect_to review_path(@review)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy 
    flash[:warning] = "Ваш комментарий удален!"
    redirect_to review_path(@review)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_review!
    @review = Review.find params[:review_id]
  end

  def set_comment!
    @comment = @review.comments.find params[:id]
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  def index
  
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # избегаем дублирования кода с помощью before_action и находим review и comment по id до запуска контроллера. Важен порядок Экшенов!
  before_action :find_review, only: %i[edit show update destroy]
  
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new review_params
    if @review.save
      flash[:warning] = "Ваш отзыв отправлен!"
      redirect_to reviews_path
    else 
      render :new
    end
  end

  def edit
    
  end

  def show
    # Создаем в памяти новый образец класса comment и сразу же привязываем его к конкретному отзыву(@review). 
    # Делается это все для того, чтобы не создавать отдельную форму для комментариев, а сразу отображать их в show вместе с отзывами.
    @comment = @review.comments.build
    # Находим все комментарии в БД и сортируем их по убыванию(самый свежий ответ будет самым первым)
    @comments = @review.comments.order created_at: :desc 
  end

  def update
    if @review.update review_params
      flash[:warning] = "Ваш отзыв обновлен!"
      redirect_to reviews_path
    else
      render :edit
    end
  end

  def destroy
    if @review.destroy 
      flash[:warning] = "Ваш отзыв удален!"
      redirect_to reviews_path
    else 
      flash[:warning] = "Произошла ошибка!"
      redirect_to reviews_path
    end
  end

  private 
  
  def review_params
    params.require(:review).permit(:body)
  end

  def find_review
    @review = Review.find params[:id]
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # избегаем дублирования кода с помощью before_action и находим review и comment по id до запуска контроллера. Важен порядок Экшенов!
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: %i[edit update]
  before_action :set_user!, only: %i[edit update]

  def edit 
  end

  def update
    if @user.update user_params
      flash[:warning] = 'Ваш профиль успешно обновлен!'
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in @user
      flash[:warning] = "Вы успешно зарегистрироались!, #{@user.name}"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def set_user!
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :old_password)
  end
end

app/helpers/abouts_helper.rb
# frozen_string_literal: true

module AboutsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Ремонт стиральных машин"
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/prices_helper.rb
# frozen_string_literal: true

module PricesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/abouts/index.html.erb
<% provide :clients_title, 'О нас' %>

<container class="container">
<container class="cont">
	
	<div class="entry-content"><h1>О нашем сервисе</h1> 
    <img src="https://trs13.ru/wp-content/uploads/2018/07/tehnoremservis2.jpg">
      <p>Сервисный центр <strong>«У Сани»</strong> с 2008 года оказывает услуги по ремонту бытовой техники и электроники в Саранске.</p>
      <p>Основа нашего коллектива — это опытные мастера с трудовым стажем не менее 5-ти лет, которые 7 дней в неделю готовы 
         прийти к Вам на помощь и восстановить работоспособность техники даже в самых сложных случаях.</p>
      <p>Для нас важен каждый клиент, поэтому мы сделаем все от нас зависящее чтобы вы остались на 100% довольны качеством 
         нашего сервиса и могли с уверенностью рекомендовать нас своим друзьям и знакомым.</p>
        <h2>Почему выбирают нас:</h2>
      <ul>
        <li>Гарантия на все виды работ до 12-ти месяцев;</li>
        <li>Бесплатный выезд и диагностика (при заказе ремонта);</li>
        <li>Собственный склад запчастей;</li>
        <li>Оперативность;</li>
        <li>Прозрачная цена на услуги;</li>
        <li>Культурные и вежливые мастера;</li>
        <li>Работаем без выходных и праздников;</li>
      </ul>

  </div>
</container>

app/views/reviews/_form.html.erb
<%= render 'shared/errors', object: @review %>


<%= form_with model: @review do |f| %>
<div class="cont_review">
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
    </div>
    
    <div class="col-sm-10">
    <%= f.text_area :body, class: "form-control", required: true, minlenght: 5 %>
    </div>
  </div>

    <%= f.submit "Отправить", class: "btn btn-lg"%>
<% end %>
</div>

app/views/reviews/edit.html.erb
<container class="your_edit_reviews">
  <% provide :clients_title, 'Редактирование отзыва' %>
    <h1 class="mb-4"> Редактировать отзыв </h1>
  <%= render 'form' %>
</container>

app/views/reviews/index.html.erb
  <% provide :clients_title, 'Все отзывы' %>
  <container class="review">
    <h1 class="mb-4"> Ваши отзывы </h1>
    <div class="review_btn">
  <%= link_to 'Оставить отзыв', new_review_path, class: 'btn btn-lg' %></div>
  <%# Перебираем все ответы %>
    <% @reviews.each do |review| %>
      <article class="card mt-3">
        <div class="card-body">
          <h4 class="text"><i><%= truncate review.body, length: 270, omission:'...' %></i></h4>
          <section class="card-text">
          <time datetime="<%= review.formatted_created_at %>">
          <small><%= review.formatted_created_at %></small></time><br>
          <div class="col_btn">

            <%# Передаем объект(review) для того чтобы подставить конкретный id в url. Метод .id вызывается автоматически.%>
            <a><%= link_to 'Показать полностью', review_path(review), class: 'btn mt-2 mb-1'%></a>
            <a> <%= link_to 'Редактировать', edit_review_path(review), class: 'btn mt-2 mb-2' %></a>
            <a><%= link_to 'Удалить', review_path(review), class: 'btn mt-2 mb-0', data: {method: :delete, confirm: 'Вы точно уверены?'} %></a></div>
        </div>
      </article>
  <% end %>
</container>

app/views/reviews/new.html.erb
<% provide :clients_title, 'Оставить отзыв' %>

<container class="your_reviews">
  <h1 class="mb-4"> Оставьте свой отзыв </h1>
  <%= render 'form' %>
</container>

app/views/reviews/show.html.erb
<% provide :clients_title, 'Отзыв' %>

<container class="show">
  <div class="show_review">
    <article class="card mt-3">
      <div class="card-body">
          <h1 class="mb-1"><i><%= @review.body %></i> </h1>
          <time datetime="<%= @review.formatted_created_at %>">
          <%= @review.formatted_created_at %></time>
        <div class="coll_btn">
        <%# Передаем объект(review) для того чтобы подставить конкретный id в url. Метод .id вызывается автоматически.%>
        <%# <%= link_to 'Показать полностью', review_path(@review), class: 'btn btn mt-2 mb-1'%> 
          <%= link_to 'Редактировать', edit_review_path(@review), class: 'btn btn mt-2 mb-2' %>
        <%= link_to 'Удалить', review_path(@review), class: 'btn btn mt-2 mb-0', data: {method: :delete, confirm: 'Вы точно уверены?'} %>
        </div>
      </div>
    
      <%= render 'comments/form' %>
        <h2 class="mb-1">Комментарии</h2>
        <%# Перебираем все комментарии %>
          <% @comments.each do |comment|%>
          <div>
          <div class="cherta">
          <hr class="my-3">
          </div>
        <i class="comment"><%= comment.body %></i>
      <div class="comment_time">
          <time datetime="<%= comment.formatted_created_at %>">
        <%= comment.formatted_created_at %></time>
      </div>
      <div class="comment_btn">
      <%# Передаем массив содержащий в себе объект(@review и comment) для того чтобы подставить конкретный id в url. Метод .id вызывается автоматически.%>
        <%= link_to 'Редактировать', edit_review_comment_path(@review, comment), class: 'btn btn-long' %>
        <%= link_to 'Удалить', review_comment_path(@review, comment), class: 'btn btn-sm',
                               data: {method: :delete, confirm: "Вы уверены?"} %>
      </div>
        
      </div>
      
        <% end %>
    </article>
  </div>
</container>