config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create edit update]

  root 'clients#index'

  resources :contacts
  resources :abouts
  resources :services
  resources :reviews do
    resources :comments, except: %i[new show]
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :phone, presence :true, uniqueness: true, length: {minimum:11}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review

  validates :body, presence: true, length: {minimum: 5}
 
  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: {minimum:2}
  validates :email, presence: true, uniqueness: true
  validates :body, presence: true, length: {minimum: 5}
end

app/models/review.rb
class Review < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :body, presence: true, length: {minimum: 5}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :old_password, :remember_token

  has_secure_password validations: false

  validate :password_presence
  validate :correct_old_password, on: :update, if: -> { password.present? }
  validates :password, confirmation: true, allow_blank: true

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validate :password_complexity

  def remember_me
    self.remember_token = SecureRandom.urlsafe_base64
    update_column :remember_token_digest, digest(remember_token)
  end

  def forget_me
    update_column :remember_token_digest, nil
    self.remember_token = nil
  end

  def remember_token_authenticated?(remember_token)
    return false unless remember_token_digest.present?

    BCrypt::Password.new(remember_token_digest).is_password?(remember_token)
  end

  private

  def digest(string)
    cost = if ActiveModel::SecurePassword
              .min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add :old_password, 'не верный'
  end

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

    msg = 'требование сложности не соблюдено. Длина должна быть от 8 до 70 символов' \
    'и включать: 1 прописную, 1 строчную, 1 цифру и 1 специальный символ.'

    errors.add :password, msg
  end

  def password_presence
    errors.add(:password, :blank) if password_digest.blank?
  end
end

app/controllers/abouts_controller.rb
# frozen_string_literal: true

class AboutsController < ApplicationController
  def index
    
  end
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  def index; 

  end

  def def(_new)
    @user = User.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # избегаем дублирования кода с помощью before_action и находим review и comment по id до запуска контроллера. Важен порядок Экшенов!
  before_action :find_review, only: %i[edit show update destroy]
  
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new review_params
    if @review.save
      flash[:warning] = "Ваш отзыв отправлен!"
      redirect_to reviews_path
    else 
      render :new
    end
  end

  def edit
    
  end

  def show
    # Создаем в памяти новый образец класса comment и сразу же привязываем его к конкретному отзыву(@review). 
    # Делается это все для того, чтобы не создавать отдельную форму для комментариев, а сразу отображать их в show вместе с отзывами.
    @comment = @review.comments.build
    # Находим все комментарии в БД и сортируем их по убыванию(самый свежий ответ будет самым первым)
    @comments = @review.comments.order created_at: :desc 
  end

  def update
    if @review.update review_params
      flash[:warning] = "Ваш отзыв обновлен!"
      redirect_to reviews_path
    else
      render :edit
    end
  end

  def destroy
    if @review.destroy 
      flash[:warning] = "Ваш отзыв удален!"
      redirect_to reviews_path
    else 
      flash[:warning] = "Произошла ошибка!"
      redirect_to reviews_path
    end
  end

  private 
  
  def review_params
    params.require(:review).permit(:body)
  end

  def find_review
    @review = Review.find params[:id]
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # избегаем дублирования кода с помощью before_action и находим review и comment по id до запуска контроллера. Важен порядок Экшенов!
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: %i[edit update]
  before_action :set_user!, only: %i[edit update]

  def edit 
  end

  def update
    if @user.update user_params
      flash[:warning] = 'Ваш профиль успешно обновлен!'
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in @user
      flash[:warning] = "Вы успешно зарегистрироались!, #{@user.name}"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def set_user!
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :old_password)
  end
end

app/helpers/abouts_helper.rb
# frozen_string_literal: true

module AboutsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Ремонт стиральных машин"
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/prices_helper.rb
# frozen_string_literal: true

module PricesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:clients_title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="black-shadow">
      <div class="logo"><span><%= link_to image_tag("Wash.png"), root_path%></span>
      </div>
        <div class="flash" style="position: absolute; display: flex; top: 100px; width: 25vh; text-align: center; font-size: 1.2em, margin: auto;">
        <% flash.each do |k,v| %>
        <%=tag.div v, class: "alert alert-#{k}", role: 'alert'%>
        <% end %>
        </div>
          <nav class="navigation">
            <span><%= link_to 'О нас', abouts_path%></span>
            <span><%= link_to 'Услуги', services_path%></span>
            <span><%= link_to 'Контакты', contacts_path%></span>
            <span><%= link_to 'Отзывы',  reviews_path%></span>
              <% if user_signed_in? %>
            <span class="dropdown", href="#">
            <button onclick="myFunction()" class="dropbtn btnLogin-popup btn-lg"><%= current_user.name%></button>
          <div id="myDropdown" class="dropdown-content">
            <span class="edit"><%= link_to 'Редактировать', edit_user_path(current_user) %></span>
            <span class="exit"><%= link_to 'Выйти', session_path, data: {method: :delete} %></span>
              <% else %>
            <button onclick="myFunction()" class="dropbtn btnLogin-popup btn-lg">Регистрация</button>
          <div id="myDropdown" class="dropdown-content">
            <span span><%= link_to 'Зарегистрироваться', new_user_path%></span>
            <span><%= link_to 'Войти', new_session_path%></span>
          </div>
            <% end %>
          </nav>
          </div>
    </header>
      <%= yield %>      
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <main>
    <div class="py-3 ">
      <h2>Ремонт стиральных машин на дому</h2>
      <p class="lead">Узнайте возможную причину неисправности и<br> 
                      стоимость ремонта по телефону <strong>+7 (927) 463-34-22</strong><br>
                      или оставьте свой номер и мастер Вам перезвонит</p>

<%= form_with model: @page do |f| %>
  <div>
  <div class="col-sm-3">
      <%= f.text_field :phone, required: true, minlength: 11, placeholder: 'Ваш телефон', class: 'form-control' %>
  </div>
</div>

  <div class="col-sm-3"><br>
      <%= f.text_field :name, required: true, minlength: 2, placeholder: 'Ваше имя', class: 'form-control' %>
  </div>
</div>

      <%= f.submit 'Заказать бесплатную консультацию', class: 'btn btn-primary btn-lg' %>
</div>
</div>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>